version: 0.2

env:
  variables:
    AWS_REGION: "us-east-1"
    ECR_REPO: "522814735019.dkr.ecr.us-east-1.amazonaws.com/employeeback"
    IMAGE_TAG: "latest"

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo Installing Maven...
      - yum install -y maven
      - echo Installing Trivy for image scanning...
      - rpm -ivh https://github.com/aquasecurity/trivy/releases/latest/download/trivy_0.50.1_Linux-64bit.rpm || true

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REPO

  build:
    commands:
      - echo Running SonarQube analysis and building project...
      - mvn clean verify sonar:sonar -Dsonar.projectKey=employeeyash -Dsonar.host.url=http://18.214.25.48 -Dsonar.login=sqp_d113cb3434eb018a3e43d768747ead82009b3567
      - echo Building Docker image...
      - docker build -t $ECR_REPO:$IMAGE_TAG .
      - echo Scanning Docker image with Trivy...
      - trivy image --exit-code 1 --severity HIGH,CRITICAL $ECR_REPO:$IMAGE_TAG || {
            echo "Vulnerabilities found! Failing the build.";
            exit 1;
        }

  post_build:
    commands:
      - echo Pushing Docker image to ECR...
      - docker push $ECR_REPO:$IMAGE_TAG

      - echo Updating Kubernetes manifests...
      - mkdir -p k8s-out
      - sed "s|IMAGE_PLACEHOLDER|$ECR_REPO:$IMAGE_TAG|g" k8s/backend-deployment.yaml > k8s-out/deployment.yaml
      - cp k8s/backend-service.yaml k8s-out/service.yaml
      - cp k8s/ingress.yaml k8s-out/ingress.yaml
      - cp k8s/namespace.yaml k8s-out/namespace.yaml

artifacts:
  base-directory: k8s-out
  files:
    - deployment.yaml
    - service.yaml
    - ingress.yaml
    - namespace.yaml
